import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "./components/header/Header";
import { NextUIProvider } from "@nextui-org/react";
import { ViewTransitions } from "next-view-transitions";
const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <ViewTransitions>
      <html lang="en"  >
        <body className={inter.className}>
          <NextUIProvider >
            <Header />
            {children}
            {/* <TransitionPage /> */}
          </NextUIProvider>
        </body>
      </html>
    </ViewTransitions>
  );
}
